name: Go Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, master, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.24", "1.24.4"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
            ${{ runner.os }}-go-

      - name: Verify Go installation and modules
        run: |
          go version
          go env GOVERSION GOMOD GOPATH
          ls -la
          cat go.mod
          go mod verify

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: |
          go test -v -race -coverprofile=coverage.out ./test/service/unit
          go tool cover -func=coverage.out

      - name: Run go vet
        run: go vet ./test/service/unit

      - name: Run go fmt check
        run: |
          if [ "$(gofmt -s -l ./test/service/unit | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted:"
            gofmt -s -l ./test/service/unit
            exit 1
          fi
